const translations = {
  es: {
    "nav-register": "Registro",
    "nav-services": "Servicios",
    "nav-how": "Cómo funciona",
    "nav-payments": "Pagos",
    "nav-contact": "Contacto",
    "hero-title": "Tu mascota merece lo mejor",
    "hero-subtitle": "Cuando no puedes estar, nosotros lo cuidamos como si fuera nuestro.",
    "hero-btn1": "Regístrate gratis",
    "hero-btn2": "Soy refugio o asociación",
    "register-title": "¿Cómo quieres unirte a CuidaMiHuella?",
    "register-subtitle": "Elige tu perfil y comienza a cuidar, ser cuidado o ayudar.",
    "type1": "Cuidador",
    "type1-desc": "Buscas una mascota para cuidar temporalmente o probar una adopción.",
    "type2": "Dueño",
    "type2-desc": "Necesitas que cuiden de tu mascota mientras no puedes estar.",
    "type3": "Asociación / Refugio",
    "type3-desc": "Publica animales, recibe donaciones y gestiona adopciones.",
    "services-title": "Cuidado hecho con cariño",
    "services-subtitle": "Para cada necesidad, una solución humana",
    "basic": "Básico",
    "price-basic": "10 €/día",
    "basic-1": "Alimentación y paseo",
    "basic-2": "Compañía afectuosa",
    "basic-3": "Ideal para familias ocupadas",
    "standard": "Estándar",
    "price-standard": "15 €/día",
    "std-1": "Seguimiento con fotos",
    "std-2": "Notificaciones diarias",
    "std-3": "Cuidado personalizado",
    "premium": "Premium",
    "price-premium": "20 €/día",
    "premium-badge": "Premium",
    "prem-1": "Recogida a domicilio",
    "prem-2": "Guardián verificado (4.8★+)",
    "prem-3": "Ideal para vacaciones familiares",
    "express": "Premium Express",
    "price-express": "Día 1: 50 €<br>Resto: 15 €/día",
    "express-badge": "Express 24/7",
    "exp-1": "Atención continua",
    "exp-2": "Soporte 24h",
    "exp-3": "Recogida inmediata",
    "service-note": "✅ Fotos y perfiles visibles. 💬 Chat solo tras pago.",
    "how-title": "Así de simple",
    "how-subtitle": "Conexión, confianza y cuidado",
    "step1": "Regístrate y explora",
    "step1-desc": "Accede a todos los perfiles, fotos y anuncios de mascotas. Todo es visible, pero el contacto está bloqueado.",
    "step2": "Elige y paga",
    "step2-desc": "Selecciona un cuidador, dueño o refugio y realiza el pago seguro para desbloquear la comunicación.",
    "step3": "Chatea y coordina",
    "step3-desc": "Acceso inmediato a un chat privado para organizar la guarda, adopción o entrega.",
    "step4": "Cuida con confianza",
    "step4-desc": "Seguimiento, reseñas y soporte durante todo el proceso.",
    "payment-title": "Pago seguro y flexible",
    "payment-subtitle": "Elige el método que más te convenga. Todos están protegidos con encriptación SSL y 3D Secure.",
    "cta-title": "Únete a una comunidad que cuida con el corazón",
    "cta-subtitle": "Más de 2.000 familias ya confían en nosotros.",
    "cta-btn1": "Regístrate gratis",
    "cta-btn2": "partners@cuidamihuella.com",
    "stories-title": "Historias de amor verdadero",
    "stories-subtitle": "Donde cada mirada dice más que mil palabras",
    "story1-title": "Lucía y Max",
    "story1-desc": "\"Max es mi mejor amigo. Cuando mamá viajó, CuidaMiHuella lo cuidó como si fuera suyo.\"",
    "story2-title": "La familia Ruiz",
    "story2-desc": "\"Gracias al servicio premium, Bruno tuvo compañía mientras estábamos de vacaciones. ¡Volvió feliz!\"",
    "footer-copyright": "© 2025 CuidaMiHuella – Donde cada huella cuenta.",
    "footer-availability": "Disponible en toda España | Próximamente en Europa"
  },
  fr: {
    "nav-register": "Inscription",
    "nav-services": "Services",
    "nav-how": "Comment ça marche ?",
    "nav-payments": "Paiements",
    "nav-contact": "Contact",
    "hero-title": "Votre animal de compagnie mérite le meilleur",
    "hero-subtitle": "Quand vous ne pouvez pas être là, nous le gardons comme si c’était le nôtre.",
    "hero-btn1": "Inscrivez-vous gratuitement",
    "hero-btn2": "Je suis refuge ou association",
    "register-title": "Comment souhaitez-vous rejoindre CuidaMiHuella ?",
    "register-subtitle": "Choisissez votre profil et commencez à prendre soin, être pris en charge ou aider.",
    "type1": "Gardien",
    "type1-desc": "Vous cherchez un animal à garder temporairement ou à tester pour adoption.",
    "type2": "Propriétaire",
    "type2-desc": "Vous avez besoin qu’on s’occupe de votre animal pendant votre absence.",
    "type3": "Association / Refuge",
    "type3-desc": "Publiez des animaux, recevez des dons et gérez les adoptions.",
    "services-title": "Des soins faits avec tendresse",
    "services-subtitle": "Une solution humaine pour chaque besoin",
    "basic": "Service de base",
    "price-basic": "10 €/jour",
    "basic-1": "Nourriture et promenade",
    "basic-2": "Compagnie affectueuse",
    "basic-3": "Idéal pour familles occupées",
    "standard": "Standard",
    "price-standard": "15 €/jour",
    "std-1": "Suivi avec photos",
    "std-2": "Notifications quotidiennes",
    "std-3": "Soins personnalisés",
    "premium": "Premium",
    "price-premium": "20 €/jour",
    "premium-badge": "Premium",
    "prem-1": "Récupération à domicile",
    "prem-2": "Gardien vérifié (4,8★+)",
    "prem-3": "Idéal pour vacances en famille",
    "express": "Premium Express",
    "price-express": "Jour 1 : 50 €<br>Reste : 15 €/jour",
    "express-badge": "Express 24/7",
    "exp-1": "Attention continue",
    "exp-2": "Support 24h",
    "exp-3": "Récupération immédiate",
    "service-note": "✅ Photos et profils visibles. 💬 Chat uniquement après paiement.",
    "how-title": "Aussi simple que ça",
    "how-subtitle": "Connexion, confiance et soin",
    "step1": "Inscrivez-vous et explorez",
    "step1-desc": "Accédez à tous les profils, photos et annonces d’animaux. Tout est visible, mais le contact est bloqué.",
    "step2": "Choisissez et payez",
    "step2-desc": "Sélectionnez un gardien, propriétaire ou refuge et effectuez le paiement sécurisé pour débloquer la communication.",
    "step3": "Discutez et coordonnez",
    "step3-desc": "Accès immédiat à un chat privé pour organiser la garde, l’adoption ou la remise.",
    "step4": "Prenez soin en toute confiance",
    "step4-desc": "Suivi, avis et assistance pendant tout le processus.",
    "payment-title": "Paiement sécurisé et flexible",
    "payment-subtitle": "Choisissez la méthode qui vous convient le mieux. Tous sont protégés par chiffrement SSL et 3D Secure.",
    "cta-title": "Rejoignez une communauté qui prend soin avec le cœur",
    "cta-subtitle": "Plus de 2 000 familles nous font déjà confiance.",
    "cta-btn1": "Inscrivez-vous gratuitement",
    "cta-btn2": "partners@cuidamihuella.com",
    "stories-title": "Histoires d’amour sincère",
    "stories-subtitle": "Où chaque regard en dit plus que mille mots",
    "story1-title": "Lucía et Max",
    "story1-desc": "« Max est mon meilleur ami. Quand maman est partie en voyage, CuidaMiHuella s’est occupé de lui comme si c’était le sien. »",
    "story2-title": "La famille Ruiz",
    "story2-desc": "« Grâce au service premium, Bruno a eu de la compagnie pendant nos vacances. Il est revenu heureux ! »",
    "footer-copyright": "© 2025 CuidaMiHuella – Là où chaque empreinte compte.",
    "footer-availability": "Disponible en Espagne | Bientôt en Europe"
  },
  en: {
    "nav-register": "Register",
    "nav-services": "Services",
    "nav-how": "How it works",
    "nav-payments": "Payments",
    "nav-contact": "Contact",
    "hero-title": "Your pet deserves the best",
    "hero-subtitle": "When you can’t be there, we care for them as if they were ours.",
    "hero-btn1": "Sign up for free",
    "hero-btn2": "I’m a shelter or association",
    "register-title": "How would you like to join CuidaMiHuella?",
    "register-subtitle": "Choose your profile and start caring, being cared for, or helping.",
    "type1": "Caregiver",
    "type1-desc": "You’re looking for a pet to care for temporarily or to try adoption.",
    "type2": "Owner",
    "type2-desc": "You need someone to care for your pet while you’re away.",
    "type3": "Association / Shelter",
    "type3-desc": "Publish animals, receive donations, and manage adoptions.",
    "services-title": "Care made with love",
    "services-subtitle": "A human solution for every need",
    "basic": "Basic",
    "price-basic": "10 €/day",
    "basic-1": "Feeding and walk",
    "basic-2": "Affectionate companionship",
    "basic-3": "Perfect for busy families",
    "standard": "Standard",
    "price-standard": "15 €/day",
    "std-1": "Photo updates",
    "std-2": "Daily notifications",
    "std-3": "Personalized care",
    "premium": "Premium",
    "price-premium": "20 €/day",
    "premium-badge": "Premium",
    "prem-1": "Home pickup",
    "prem-2": "Verified caregiver (4.8★+)",
    "prem-3": "Ideal for family vacations",
    "express": "Premium Express",
    "price-express": "Day 1: 50 €<br>Rest: 15 €/day",
    "express-badge": "Express 24/7",
    "exp-1": "Continuous care",
    "exp-2": "24/7 support",
    "exp-3": "Immediate pickup",
    "service-note": "✅ Photos and profiles visible. 💬 Chat only after payment.",
    "how-title": "That simple",
    "how-subtitle": "Connection, trust, and care",
    "step1": "Sign up and explore",
    "step1-desc": "Access all profiles, photos, and pet listings. Everything is visible, but contact is locked.",
    "step2": "Choose and pay",
    "step2-desc": "Select a caregiver, owner, or shelter and make a secure payment to unlock communication.",
    "step3": "Chat and coordinate",
    "step3-desc": "Immediate access to a private chat to arrange care, adoption, or handover.",
    "step4": "Care with confidence",
    "step4-desc": "Tracking, reviews, and support throughout the process.",
    "payment-title": "Secure and flexible payment",
    "payment-subtitle": "Choose the method that suits you best. All are protected with SSL encryption and 3D Secure.",
    "cta-title": "Join a community that cares with heart",
    "cta-subtitle": "Over 2,000 families already trust us.",
    "cta-btn1": "Sign up for free",
    "cta-btn2": "partners@cuidamihuella.com",
    "stories-title": "True love stories",
    "stories-subtitle": "Where every glance says more than a thousand words",
    "story1-title": "Lucía and Max",
    "story1-desc": "\"Max is my best friend. When Mom traveled, CuidaMiHuella cared for him as if he were theirs.\"",
    "story2-title": "The Ruiz Family",
    "story2-desc": "\"Thanks to the premium service, Bruno had company while we were on vacation. He came back happy!\"",
    "footer-copyright": "© 2025 CuidaMiHuella – Where every pawprint matters.",
    "footer-availability": "Available across Spain | Coming soon to Europe"
  },
  de: {
    "nav-register": "Registrieren",
    "nav-services": "Dienstleistungen",
    "nav-how": "Wie funktioniert es?",
    "nav-payments": "Zahlungen",
    "nav-contact": "Kontakt",
    "hero-title": "Ihr Haustier verdient das Beste",
    "hero-subtitle": "Wenn Sie nicht da sein können, kümmern wir uns darum, als wäre es unseres.",
    "hero-btn1": "Kostenlos anmelden",
    "hero-btn2": "Ich bin ein Tierheim oder Verein",
    "register-title": "Wie möchten Sie CuidaMiHuella beitreten?",
    "register-subtitle": "Wählen Sie Ihr Profil und beginnen Sie zu betreuen, betreut zu werden oder zu helfen.",
    "type1": "Betreuer",
    "type1-desc": "Sie suchen ein Tier, das Sie vorübergehend betreuen oder zur Adoption testen möchten.",
    "type2": "Besitzer",
    "type2-desc": "Sie brauchen jemanden, der sich um Ihr Tier kümmert, während Sie abwesend sind.",
    "type3": "Verein / Tierheim",
    "type3-desc": "Veröffentlichen Sie Tiere, erhalten Sie Spenden und verwalten Sie Adoptionen.",
    "services-title": "Pflege mit Herz",
    "services-subtitle": "Eine menschliche Lösung für jedes Bedürfnis",
    "basic": "Basis",
    "price-basic": "10 €/Tag",
    "basic-1": "Fütterung und Spaziergang",
    "basic-2": "Liebevolle Gesellschaft",
    "basic-3": "Ideal für beschäftigte Familien",
    "standard": "Standard",
    "price-standard": "15 €/Tag",
    "std-1": "Foto-Updates",
    "std-2": "Tägliche Benachrichtigungen",
    "std-3": "Individuelle Betreuung",
    "premium": "Premium",
    "price-premium": "20 €/Tag",
    "premium-badge": "Premium",
    "prem-1": "Abholung zu Hause",
    "prem-2": "Verifizierter Betreuer (4,8★+)",
    "prem-3": "Ideal für Familienurlaub",
    "express": "Premium Express",
    "price-express": "Tag 1: 50 €<br>Weitere: 15 €/Tag",
    "express-badge": "Express 24/7",
    "exp-1": "Kontinuierliche Betreuung",
    "exp-2": "24/7-Support",
    "exp-3": "Sofortige Abholung",
    "service-note": "✅ Fotos und Profile sichtbar. 💬 Chat erst nach Zahlung.",
    "how-title": "So einfach",
    "how-subtitle": "Verbindung, Vertrauen und Fürsorge",
    "step1": "Registrieren und erkunden",
    "step1-desc": "Greifen Sie auf alle Profile, Fotos und Tieranzeigen zu. Alles ist sichtbar, aber der Kontakt ist gesperrt.",
    "step2": "Wählen und bezahlen",
    "step2-desc": "Wählen Sie einen Betreuer, Besitzer oder ein Tierheim aus und tätigen Sie eine sichere Zahlung, um die Kommunikation freizuschalten.",
    "step3": "Chatten und koordinieren",
    "step3-desc": "Sofortiger Zugang zu einem privaten Chat, um Betreuung, Adoption oder Übergabe zu organisieren.",
    "step4": "Mit Vertrauen betreuen",
    "step4-desc": "Verfolgung, Bewertungen und Unterstützung während des gesamten Prozesses.",
    "payment-title": "Sichere und flexible Zahlung",
    "payment-subtitle": "Wählen Sie die Methode, die Ihnen am besten passt. Alle sind mit SSL-Verschlüsselung und 3D Secure geschützt.",
    "cta-title": "Treten Sie einer Gemeinschaft bei, die mit Herz sorgt",
    "cta-subtitle": "Über 2.000 Familien vertrauen uns bereits.",
    "cta-btn1": "Kostenlos anmelden",
    "cta-btn2": "partners@cuidamihuella.com",
    "stories-title": "Geschichten wahrer Liebe",
    "stories-subtitle": "Wo jeder Blick mehr sagt als tausend Worte",
    "story1-title": "Lucía und Max",
    "story1-desc": "„Max ist mein bester Freund. Als Mama verreist war, hat CuidaMiHuella sich um ihn gekümmert, als wäre er ihr eigener.“",
    "story2-title": "Die Familie Ruiz",
    "story2-desc": "„Dank des Premium-Service hatte Bruno Gesellschaft, während wir im Urlaub waren. Er kam glücklich zurück!“",
    "footer-copyright": "© 2025 CuidaMiHuella – Wo jeder Pfotenabdruck zählt.",
    "footer-availability": "In ganz Spanien verfügbar | Bald in Europa"
  },
  it: {
    "nav-register": "Registrazione",
    "nav-services": "Servizi",
    "nav-how": "Come funziona",
    "nav-payments": "Pagamenti",
    "nav-contact": "Contatto",
    "hero-title": "Il tuo animale domestico merita il meglio",
    "hero-subtitle": "Quando non puoi esserci, ci prendiamo cura di lui come se fosse nostro.",
    "hero-btn1": "Registrati gratis",
    "hero-btn2": "Sono un rifugio o un'associazione",
    "register-title": "Come vuoi unirti a CuidaMiHuella?",
    "register-subtitle": "Scegli il tuo profilo e inizia a prenderti cura, essere curato o aiutare.",
    "type1": "Custode",
    "type1-desc": "Cerchi un animale da accudire temporaneamente o provare per l'adozione.",
    "type2": "Proprietario",
    "type2-desc": "Hai bisogno che qualcuno si prenda cura del tuo animale mentre sei via.",
    "type3": "Associazione / Rifugio",
    "type3-desc": "Pubblica animali, ricevi donazioni e gestisci adozioni.",
    "services-title": "Cura fatta con affetto",
    "services-subtitle": "Una soluzione umana per ogni esigenza",
    "basic": "Base",
    "price-basic": "10 €/giorno",
    "basic-1": "Alimentazione e passeggiata",
    "basic-2": "Compagnia affettuosa",
    "basic-3": "Ideale per famiglie impegnate",
    "standard": "Standard",
    "price-standard": "15 €/giorno",
    "std-1": "Aggiornamenti con foto",
    "std-2": "Notifiche giornaliere",
    "std-3": "Cura personalizzata",
    "premium": "Premium",
    "price-premium": "20 €/giorno",
    "premium-badge": "Premium",
    "prem-1": "Ritiro a domicilio",
    "prem-2": "Custode verificato (4,8★+)",
    "prem-3": "Ideale per vacanze in famiglia",
    "express": "Premium Express",
    "price-express": "Giorno 1: 50 €<br>Resto: 15 €/giorno",
    "express-badge": "Express 24/7",
    "exp-1": "Cura continua",
    "exp-2": "Assistenza 24/7",
    "exp-3": "Ritiro immediato",
    "service-note": "✅ Foto e profili visibili. 💬 Chat solo dopo il pagamento.",
    "how-title": "Così semplice",
    "how-subtitle": "Connessione, fiducia e cura",
    "step1": "Registrati ed esplora",
    "step1-desc": "Accedi a tutti i profili, foto e annunci di animali. Tutto è visibile, ma il contatto è bloccato.",
    "step2": "Scegli e paga",
    "step2-desc": "Seleziona un custode, proprietario o rifugio e effettua il pagamento sicuro per sbloccare la comunicazione.",
    "step3": "Chatta e coordina",
    "step3-desc": "Accesso immediato a una chat privata per organizzare la custodia, l'adozione o la consegna.",
    "step4": "Prenditi cura con fiducia",
    "step4-desc": "Tracciamento, recensioni e supporto durante tutto il processo.",
    "payment-title": "Pagamento sicuro e flessibile",
    "payment-subtitle": "Scegli il metodo che preferisci. Tutti sono protetti con crittografia SSL e 3D Secure.",
    "cta-title": "Unisciti a una comunità che cura con il cuore",
    "cta-subtitle": "Oltre 2.000 famiglie si fidano già di noi.",
    "cta-btn1": "Registrati gratis",
    "cta-btn2": "partners@cuidamihuella.com",
    "stories-title": "Storie d’amore vero",
    "stories-subtitle": "Dove ogni sguardo dice più di mille parole",
    "story1-title": "Lucía e Max",
    "story1-desc": "«Max è il mio migliore amico. Quando mamma è partita, CuidaMiHuella si è preso cura di lui come se fosse suo.»",
    "story2-title": "La famiglia Ruiz",
    "story2-desc": "«Grazie al servizio premium, Bruno ha avuto compagnia mentre eravamo in vacanza. È tornato felice!»",
    "footer-copyright": "© 2025 CuidaMiHuella – Dove ogni impronta conta.",
    "footer-availability": "Disponibile in tutta la Spagna | Prossimamente in Europa"
  }
};

function setLanguage(lang) {
  document.documentElement.lang = lang;
  const elements = document.querySelectorAll('[data-key]');
  elements.forEach(el => {
    const key = el.getAttribute('data-key');
    if (translations[lang] && translations[lang][key]) {
      el.innerHTML = translations[lang][key];
    }
  });
}

document.querySelectorAll('.lang-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    const lang = btn.getAttribute('data-lang');
    setLanguage(lang);
    localStorage.setItem('preferred-lang', lang);
  });
});

document.addEventListener('DOMContentLoaded', () => {
  const savedLang = localStorage.getItem('preferred-lang') || 
                    navigator.language.split('-')[0] || 'es';
  if (translations[savedLang]) {
    setLanguage(savedLang);
  } else {
    setLanguage('es');
  }
});
